// TODO: PL_ID_MANUAL -> PL_CODE_MANUAL
export const PL_ID_MANUAL = "2";

export enum POLICY_REQUEST_TYPE {
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  DEACTIVATE = "DEACTIVATE",
  ACTIVATE = "ACTIVATE",
  DELETE = "DELETE",
}
